services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: lant-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: lant-frontend
    depends_on:
      - backend
    environment:
      - VITE_API_PROXY_TARGET=http://backend:8000
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
